name: build

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - main

env:
  PRE_RELEASE: ${{ github.ref == 'refs/heads/main' && 'main' || '' }}
  SOURCE_TAG: ${{ git describe --tags --abbrev=0 }}
  GO_VERSION: "1.16"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - 
        name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: ${{ env.GO_VERSION }}
      - 
        name: Display Version
        run: |
          echo "SOURCE_TAG ${{ env.SOURCE_TAG }}"
      - 
        name: Setup caching
        uses: actions/cache@v1
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - 
        name: Install dependencies
        run: |
          go mod download
      - 
        name: Build
        run: |
          go build -o ./bin/gha-test ./cmd/gha-test
